import {DemoTransport,DEMO_MODES} from './services/demoTransport.js';
import {ObdTransport} from './services/obdTransport.js';
import {economyFromTelemetry} from './core/fuel.js';
import {TripTracker} from './core/trip.js';
import {listTrips,saveTrip,exportData} from './services/storage.js';
const $=s=>document.querySelector(s); const app=$('#app'); const demo=new DemoTransport(), obd=new ObdTransport(), trip=new TripTracker();
let transport=demo, values={}, timer, page='dashboard', history=[]; const state={connection:'DISCONNECTED',mode:'DEMO',notice:'DEMO MODE — NO VEHICLE CONNECTED',graph:'rpm',paused:false};
const fmt=(n,d=0)=>Number.isFinite(n)?n.toFixed(d):'--';
function render(){ app.innerHTML=`<header><div><b>ALTO 800</b><small>2012 PETROL · INDIA</small></div><div class="state ${state.connection.toLowerCase()}">● ${state.connection}</div><div class="readonly">READ-ONLY DIAGNOSTICS</div></header><aside><button data-page="dashboard">DASHBOARD</button><button data-page="graphs">LIVE GRAPHS</button><button data-page="diagnostics">DIAGNOSTICS</button><button data-page="engine">ENGINE STATUS</button><button data-page="history">TRIP HISTORY</button><button data-page="debug">DEBUG</button></aside><main>${pageContent()}</main><footer>${state.notice}</footer>`; bind(); }
function pageContent(){if(page==='dashboard')return dashboard();if(page==='graphs')return graphs();if(page==='diagnostics')return `<section class="panel"><h2>DIAGNOSTICS <span>READ ONLY</span></h2><p>Stored, pending, and permanent DTCs will be shown after a compatible adapter connects. No vehicle commands that modify configuration are implemented.</p><div class="empty">NO DTC DATA AVAILABLE</div><p class="safety">DTC clearing is intentionally disabled because this application operates in read-only mode.</p></section>`;if(page==='engine')return `<section class="panel"><h2>ENGINE STATUS</h2><p>OBD data cannot provide a complete mechanical health assessment.</p>${['Coolant temperature','Fuel trims','Engine load','O2 sensor response','ECU/OBD voltage','Misfire-related DTCs'].map((x,i)=>`<div class="indicator"><b>${x}</b><span>${i===5?'DATA UNAVAILABLE':i===3?'INFORMATION':'NORMAL RANGE'}</span></div>`).join('')}</section>`;if(page==='history')return `<section class="panel"><h2>TRIP HISTORY</h2><div class="actions"><button id="export-json">EXPORT JSON</button><button id="export-csv">EXPORT CSV</button></div>${history.length?history.map((t,i)=>`<article class="trip"><b>TRIP #${String(history.length-i).padStart(3,'0')}</b><span>${fmt(t.distanceKm,1)} km · ${t.economy?fmt(t.economy,1)+' km/L':'Economy unavailable'} · Max ${fmt(t.maxSpeed)} km/h</span></article>`).join(''):'<div class="empty">NO RECORDED TRIPS</div>'}</section>`;return `<section class="panel"><h2>DEVELOPER DEBUG</h2><dl><dt>Mode</dt><dd>${state.mode}</dd><dt>Adapter</dt><dd>${state.mode==='DEMO'?'Demo Alto 800 adapter':'Not connected'}</dd><dt>Protocol</dt><dd>${state.mode==='DEMO'?'SIMULATED OBD-II':'Not detected'}</dd><dt>Supported PIDs</dt><dd>${state.mode==='DEMO'?'Detected in simulator':'Not detected'}</dd><dt>Safety</dt><dd>Read requests only; no CAN/write APIs exposed.</dd></dl></section>`;}
function dashboard(){const eco=economyFromTelemetry(values);return `<section class="controls"><button id="demo">START DEMO</button><select id="mode">${DEMO_MODES.map(m=>`<option ${demo.mode===m?'selected':''}>${m}</option>`).join('')}</select><button id="bluetooth">SELECT BLUETOOTH ADAPTER</button><button id="trip">${trip.active?'STOP TRIP':'START TRIP'}</button><button id="reset">RESET TRIP</button></section><section class="hero"><div class="tach"><label>RPM</label><strong>${String(Math.round(values.rpm||0)).padStart(4,'0')}</strong><small>DISPLAY REDLINE 6500 RPM</small></div><div class="speed"><label>SPEED</label><strong>${String(Math.round(values.speed||0)).padStart(3,'0')}</strong><em>km/h</em></div></section><section class="grid">${Card({title:'ENGINE TEMP',value:`${fmt(values.coolant)} °C`,note:'Configurable software warning'})}${Card({title:'FUEL',value:values.fuelLevel==null?'OBD DATA UNAVAILABLE':`${fmt(values.fuelLevel)}%`})}${Card({title:'INSTANT',value:eco.economy?`${fmt(eco.economy,1)} km/L`:'-- km/L',note:eco.source})}${Card({title:'TRIP',value:trip.summary().economy?`${fmt(trip.summary().economy,1)} km/L`:'-- km/L',note:`${fmt(trip.summary().distanceKm,1)} km recorded`})}</section><section class="telemetry">${[['LOAD','load','%'],['THROTTLE','throttle','%'],['INTAKE','intakeTemp','°C'],['VOLTAGE','voltage','V'],['STFT','stft','%'],['MAF','maf','g/s']].map(([n,k,u])=>`<div><small>${n}</small><b>${fmt(values[k],1)} ${u}</b></div>`).join('')}</section>`;}
function Card({title,value,note=''}){return `<article class="card"><small>${title}</small><strong>${value}</strong><span>${note}</span></article>`}
function graphs(){return `<section class="panel"><h2>LIVE TELEMETRY GRAPH</h2><div class="actions"><select id="metric">${['rpm','speed','coolant','throttle','load','voltage','stft'].map(x=>`<option ${state.graph===x?'selected':''}>${x}</option>`).join('')}</select><button id="pause">${state.paused?'RESUME':'PAUSE'}</button><select><option>30 sec</option><option>1 min</option><option>5 min</option><option>10 min</option></select></div><div class="graph"><div style="--level:${Math.min(95,Math.max(5,(values[state.graph]||0)/(state.graph==='rpm'?70:1)))}"></div><b>${state.graph.toUpperCase()}: ${fmt(values[state.graph],1)}</b></div><p>Scrolling graph data is kept in a bounded in-memory buffer in the production transport.</p></section>`}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});$('#demo')?.addEventListener('click',startDemo);$('#mode')?.addEventListener('change',e=>demo.mode=e.target.value);$('#bluetooth')?.addEventListener('click',connectBluetooth);$('#trip')?.addEventListener('click',toggleTrip);$('#reset')?.addEventListener('click',()=>{trip.reset();render()});$('#metric')?.addEventListener('change',e=>{state.graph=e.target.value;render()});$('#pause')?.addEventListener('click',()=>{state.paused=!state.paused;render()});$('#export-json')?.addEventListener('click',()=>exportData(history,'json'));$('#export-csv')?.addEventListener('click',()=>exportData(history,'csv'));}
async function startDemo(){transport=demo;await demo.connect();state.connection='CONNECTED';state.mode='DEMO';state.notice='DEMO MODE — NO VEHICLE CONNECTED';clearInterval(timer);timer=setInterval(()=>{if(!state.paused){values=demo.tick();const eco=economyFromTelemetry(values);trip.add({...values,fuelRateLph:eco.rateLph});if(page==='dashboard'||page==='graphs')render()}},250);render()}
async function connectBluetooth(){try{state.connection='SCANNING';state.notice='Searching for Bluetooth OBD adapters…';render();const adapters=await obd.scan();state.connection='CONNECTING';render();await obd.connect(adapters[0]);}catch(e){state.connection='ERROR';state.mode='LIVE';state.notice=e.message;render();}}
async function toggleTrip(){if(trip.active){const result=trip.stop();await saveTrip(result);history=await listTrips();}else trip.start();render()}
history=await listTrips();render();
